### ISSUE TITLE
Universal Navigate to Next Page on Form Submit

### ISSUE THREAD

**Issue by hmh84** [jameszangari/idm372#11]
Each registration page includes a form, which in terms of UX should update the DB when when click next, however, there are submit buttons to submit the form, as well as next buttons to navigate the pages (views).

We need a catch all function that will submit forms when clicking the next button, if it should behave that way.

Pages in mention:
- Name & BDay page
- Song page
- Album page
- Playlist page

**Comment by jameszangari** [comment]
I think there should be an error message like "these are required fields"
