### ISSUE TITLE
Add "Set Up: Complete" Page

### ISSUE THREAD

**Issue by jameszangari** [jameszangari/idm372#114]
<img width="178" alt="Screen Shot 2021-02-15 at 9 42 04 AM" src="https://user-images.githubusercontent.com/43617913/107959980-1093ab00-6f72-11eb-80a9-a361c769f361.png">

**Comment by hmh84** [comment]
@jameszangari This was pretty much done in other comits I worked on, anything in specific that needs to be done still here?
