### ISSUE TITLE
Next Button Overlaps Page Content

### ISSUE THREAD

**Issue by hmh84** [jameszangari/idm372#18]
![image](https://user-images.githubusercontent.com/55721189/104795012-5f82d080-5779-11eb-9d09-a4d8b97728f5.png)

Noticed this when song search results populate. Fix should address all scenarios of content overflow.

**Comment by jameszangari** [comment]
Noticed this. The div that populates the search needs to be styled like the designs (below) with overflow auto on.
<img width="402" alt="Screen Shot 2021-01-16 at 9 10 25 AM" src="https://user-images.githubusercontent.com/43617913/104814027-ad7bf080-57da-11eb-9b3b-bc50aee216ca.png">
