### ISSUE TITLE
Submit to DB Button Hidden

### ISSUE THREAD

**Issue by hmh84** [jameszangari/idm372#32]
<img width="461" alt="Screen Shot 2021-01-16 at 14 09 03" src="https://user-images.githubusercontent.com/55721189/104820664-7589a300-5804-11eb-825d-3eee71ad1371.png">
The button that actually triggers an upload to the DB is hidden under the results page.
Is the new Done button supposed to have the submit to DB functionality?

![image](https://user-images.githubusercontent.com/55721189/104820689-96ea8f00-5804-11eb-9b3a-c42759a589cd.png
)

This is an issue on the Song, Album, Playlist setup pages

**Comment by hmh84** [comment]
This is an issue on Song, Album, Playlist setup pages

**Comment by jameszangari** [comment]
@hmh84 The done button is supposed to close the modal. The modal also supposed to be hidden when search hasn't been submitted.

**Comment by hmh84** [comment]
Closing, no longer relevant since Issue-#11 was addressed.
