### ISSUE TITLE
Button Styling

### ISSUE THREAD

**Issue by RedDoormat** [jameszangari/idm372#33]

**Comment by hmh84** [comment]
![IMG_C8D2213DDD3E-1](https://user-images.githubusercontent.com/55721189/104821742-f8fac280-580b-11eb-9316-1ce49636f2f6.jpeg)
Button text is not centered in Safari FYI

**Comment by RedDoormat** [comment]
#
![dumontr_button-styling_issue33](https://user-images.githubusercontent.com/55758073/104821936-5f341500-580d-11eb-9907-a88e24ade416.png)
