### ISSUE TITLE
Set Up Deployment with Heroku

### ISSUE THREAD

**Issue by jameszangari** [jameszangari/idm372#41]
[Heroku Tutorial](https://www.youtube.com/watch?v=aUW5GAFhu6s)

**Comment by hmh84** [comment]
What host are we going with? @jameszangari

**Comment by jameszangari** [comment]
@hmh84 Gonna try and set up Heroku tomorrow. Wanted to get a little further with the dev. Seems like we are in a good spot now.

**Comment by jameszangari** [comment]
Build is live here: https://shuffle-web-app.herokuapp.com
