### ISSUE TITLE
Spotify Search Results Container Overlap

### ISSUE THREAD

**Issue by hmh84** [jameszangari/idm372#47]
Similar to Issue-#18

.o-spotify-select--group has absolute position, making it not apart of body, and causing it to overflow upwards off the page.

![image](https://user-images.githubusercontent.com/55721189/104849622-c35fe300-58b8-11eb-987e-c3a64fcf5036.png)

Scrolling up is just cut off:

<img width="902" alt="Screen Shot 2021-01-17 at 11 41 57" src="https://user-images.githubusercontent.com/55721189/104849701-2782a700-58b9-11eb-9059-ef48f64402ad.png">

**Comment by jameszangari** [comment]
`.o-spotify-select--group` needs a height to contain it.. will fix
