### ISSUE TITLE
Fix Spotify search result track image ratio

### ISSUE THREAD

**Issue by hmh84** [jameszangari/idm372#65]
Some tracks can have a non-square ratio image size, needs fixed width. Setting it to width: 50px (like the height) is too thin.

![image](https://user-images.githubusercontent.com/55721189/105546728-b9305100-5ccb-11eb-8239-3ba777655c12.png)

**Comment by jameszangari** [comment]
@hmh84 what did you search? so i can re-create the issue

**Comment by hmh84** [comment]
> @hmh84 what did you search? so i can re-create the issue

Search for "Party bangers" in Playlist search, you'll actually see too wide and too thin.
![image](https://user-images.githubusercontent.com/55721189/105565251-f0b2f380-5cf3-11eb-98b3-9520982c41c2.png)

**Comment by jameszangari** [comment]
Fixed here: https://github.com/jameszangari/idm372/pull/74/commits/50f10c912d9095629cd4f8974695db2a47fdc750
